title = "Gabriel Yeo"
baseURL = "gb3h.github.io"
languageCode = "en-us"
theme = "researcher"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT"]
enableEmoji = true
math = false  # enable KaTeX (https://katex.org/) globally

[params]
  author = "Gabriel Yeo"
  description = "About me."
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  [params.footer]
    text = "By Gabriel Yeo"
    url = "https://github.com/gb3h/gb3h.github.io"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "/resume.pdf"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
