name = "Researcher"
license = "GPL-3.0"
licenselink = "https://github.com/ojroques/hugo-researcher/blob/master/LICENSE"
description = "About Me."
tags = ["blog", "bootstrap", "clean", "minimal", "personal", "responsive", "resume", "simple"]
features = ["bootstrap", "responsive", "simple"]
homepage = "https://gabrielyeo.com"
min_version = "0.74.3"

[author]
  name = "Gabriel Yeo"
  homepage = "https://gabrielyeo.com/"

[originals]
  author = "Ankit Sultana"
  homepage = "https://github.com/ankitsultana"
  repo = "https://github.com/ankitsultana/researcher"
  name = "Olivier Roques"
  homepage = "https://oroques.dev/"
